# TODO: Change to admin1 after p-coding

poverty_rate_default:
  scrapers_with_defaults:
    - "poverty_rate_afg"
    - "poverty_rate_cmr"
    - "poverty_rate_caf"
    - "poverty_rate_tcd"
    - "poverty_rate_col"
    - "poverty_rate_cod"
    - "poverty_rate_eth"
    - "poverty_rate_hti"
    - "poverty_rate_hnd"
    - "poverty_rate_mli"
    - "poverty_rate_moz"
    - "poverty_rate_ner"
    - "poverty_rate_nga"
    - "poverty_rate_pse"
    - "poverty_rate_ukr"
  format: "xlsx"
  sheet: "Harmonised MPI Region"
  headers:
    - 5
    - 6
    - 7
    - 8
  use_hxl: False
  filter_cols:
    - "MPI data source t0 Year"
  prefilter: "MPI data source t0 Year is not None"
  input:
    - "MPI data source t0 Year"
    - "MPI data source t1 Year"
    - "Region"
    - "Multidimensional Poverty Index (MPIT) t0 Range 0 to 1"
    - "Multidimensional Poverty Index (MPIT) t1 Range 0 to 1"
    - "Multidimensional Headcount Ratio (HT) t0 % pop."
    - "Multidimensional Headcount Ratio (HT) t1 % pop."
    - "Intensity of Poverty (AT) t0 Avg % of  weighted deprivations"
    - "Intensity of Poverty (AT) t1 Avg % of  weighted deprivations"
    - "Vulnerable to poverty t0 % pop."
    - "Vulnerable to poverty t1 % pop."
    - "In severe poverty t0 % pop."
    - "In severe poverty t1 % pop."
  list:
    - "MPI data source t0 Year"
    - "MPI data source t1 Year"
    - "Region"
    - "Multidimensional Poverty Index (MPIT) t0 Range 0 to 1"
    - "Multidimensional Poverty Index (MPIT) t1 Range 0 to 1"
    - "Multidimensional Headcount Ratio (HT) t0 % pop."
    - "Multidimensional Headcount Ratio (HT) t1 % pop."
    - "Intensity of Poverty (AT) t0 Avg % of  weighted deprivations"
    - "Intensity of Poverty (AT) t1 Avg % of  weighted deprivations"
    - "Vulnerable to poverty t0 % pop."
    - "Vulnerable to poverty t1 % pop."
    - "In severe poverty t0 % pop."
    - "In severe poverty t1 % pop."
  output:
    - "year_t0"
    - "year_t1"
    - "adm1_name"
    - "multidimensional_poverty_index_t0"
    - "multidimensional_poverty_index_t1"
    - "multidimensional_headcount_ratio_t0"
    - "multidimensional_headcount_ratio_t1"
    - "intensity_of_poverty_t0"
    - "intensity_of_poverty_t1"
    - "vulnerable_to_poverty_t0"
    - "vulnerable_to_poverty_t1"
    - "in_severe_poverty_t0"
    - "in_severe_poverty_t1"
  output_hxl:
    - "#year+t0"
    - "#year+t1"
    - "#adm1+name"
    - "#poverty+index+multidimensional+t0"
    - "#poverty+index+multidimensional+t1"
    - "#poverty+headcount+ratio+t0"
    - "#poverty+headcount+ratio+t1"
    - "#poverty+intensity+t0"
    - "#poverty+intensity+t1"
    - "#poverty+vulnerable+t0"
    - "#poverty+vulnerable+t1"
    - "#poverty+severe+t0"
    - "#poverty+severe+t1"

poverty_rate_national:
  poverty_rate_afg:
    dataset: "afghanistan-mpi"
    resource: "AFG_hot.xlsx"
    admin_single: "AFG"
  poverty_rate_cmr:
    dataset: "cameroon-mpi"
    resource: "CMR_hot.xlsx"
    admin_single: "CMR"
  poverty_rate_caf:
    dataset: "central-african-republic-mpi"
    resource: "CAF_hot.xlsx"
    admin_single: "CAF"
  poverty_rate_tcd:
    dataset: "chad-mpi"
    resource: "TCD_hot.xlsx"
    admin_single: "TCD"
  poverty_rate_col:
    dataset: "colombia-mpi"
    resource: "COL_hot.xlsx"
    admin_single: "COL"
  poverty_rate_cod:
    dataset: "democratic-republic-of-the-congo-mpi"
    resource: "COD_hot.xlsx"
    admin_single: "COD"
  poverty_rate_eth:
    dataset: "ethiopia-mpi"
    resource: "ETH_hot.xlsx"
    admin_single: "ETH"
  poverty_rate_hti:
    dataset: "haiti-mpi"
    resource: "HTI_hot.xlsx"
    admin_single: "HTI"
  poverty_rate_hnd:
    dataset: "honduras-mpi"
    resource: "HND_hot.xlsx"
    admin_single: "HND"
  poverty_rate_mli:
    dataset: "mali-mpi"
    resource: "MLI_hot.xlsx"
    admin_single: "MLI"
  poverty_rate_moz:
    dataset: "mozambique-mpi"
    resource: "MOZ_hot.xlsx"
    admin_single: "MOZ"
  poverty_rate_ner:
    dataset: "niger-mpi"
    resource: "NER_hot.xlsx"
    admin_single: "NER"
  poverty_rate_nga:
    dataset: "nigeria-mpi"
    resource: "NGA_hot.xlsx"
    admin_single: "NGA"
  poverty_rate_pse:
    dataset: "state-of-palestine-mpi"
    resource: "PSE_hot.xlsx"
    admin_single: "PSE"
  poverty_rate_ukr:
    dataset: "ukraine-mpi"
    resource: "UKR_hot.xlsx"
    admin_single: "UKR"
  ################################################################################
  # The ones below only have one time point and don't follow the default settings
  ################################################################################
  poverty_rate_bfa:
    dataset: "burkina-faso-mpi"
    resource: "BFA.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "BFA"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
  poverty_rate_slv:
    dataset: "el-salvador-mpi"
    resource: "SLV.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "SLV"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
  poverty_rate_gtm:
    dataset: "guatemala-mpi"
    resource: "GTM.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "GTM"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
  poverty_rate_mmr:
    dataset: "myanmar-mpi"
    resource: "MMR.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "MMR"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
  poverty_rate_sdn:
    dataset: "sudan-mpi"
    resource: "SDN.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "SDN"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
  poverty_rate_yem:
    dataset: "yemen-mpi"
    resource: "YEM.xlsx"
    format: "xlsx"
    sheet: "MPI Region"
    admin_single: "YEM"
    number_of_timepoints: 1
    headers:
      - 5
      - 6
      - 7
      - 8
    use_hxl: False
    filter_cols:
      - "MPI data source Year"
    prefilter: "MPI data source Year is not None"
    input:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    list:
      - "MPI data source Year"
      - "Subnational  region"
      - "Multidimensional poverty by region Multidimensional Poverty Index (MPI = H*A) Range 0 to 1"
      - "Multidimensional poverty by region Headcount ratio: Population in multidimensional poverty (H) % Population"
      - "Multidimensional poverty by region Intensity of deprivation among the poor (A) Average % of weighted deprivations"
      - "Multidimensional poverty by region Vulnerable to poverty % Population"
      - "Multidimensional poverty by region In severe poverty % Population"
    output:
      - "year_t0"
      - "adm1_name"
      - "multidimensional_poverty_index_t0"
      - "multidimensional_headcount_ratio_t0"
      - "intensity_of_poverty_t0"
      - "vulnerable_to_poverty_t0"
      - "in_severe_poverty_t0"
    output_hxl:
      - "#year+t0"
      - "#adm1+name"
      - "#poverty+index+multidimensional+t0"
      - "#poverty+headcount+ratio+t0"
      - "#poverty+intensity+t0"
      - "#poverty+vulnerable+t0"
      - "#poverty+severe+t0"
