wfp_token_url: "https://api.wfp.org/token"
wfp_currencies_url: "https://api.wfp.org/vam-data-bridges/2.0.0/Currency/List"

wfp_countries:
  dataset: "global-wfp-food-prices"
  resource: "Global WFP countries"
  format: "csv"

wfp_commodity:
  dataset: "global-wfp-food-prices"
  resource: "Global WFP commodities"
  format: "csv"

wfp_market:
  dataset: "global-wfp-food-prices"
  resource: "Global WFP markets"
  format: "csv"
